--USE master
--Tạo Database
CREATE DATABASE QUANLYVKVLNCCHT
GO
USE QUANLYVKVLNCCHT
GO
-- Tạo table Công an 
CREATE TABLE CBCS(
	maCBCS VARCHAR(10),
	soHieuCAND VARCHAR(10),
	hoTen NVARCHAR(50),
	ngaySinh DATE,
	donVi NVARCHAR(50),
	capBac NVARCHAR(50),
	chucVu NVARCHAR(50),
	soDienThoai VARCHAR(10),
	CONSTRAINT pk_congan_sohieucand PRIMARY KEY (maCBCS)
);
GO

CREATE TABLE CBCS_Member(
	maCBCS_Member VARCHAR(10),
	maCBCS VARCHAR(10),
	tenTK CHAR(10),
	matKhau CHAR(10),
	CONSTRAINT pk_CBCSMember_maCBCS_Member PRIMARY KEY (maCBCS_Member),
	CONSTRAINT fk_CBCSMember_maCBCS FOREIGN KEY (maCBCS)
	REFERENCES dbo.CBCS(maCBCS)
);
GO

-- DROP TABLE CBCS -> để xoá nếu cần

CREATE TABLE CBCS_Not_Mem (
	maCBCS_Not_Mem VARCHAR(10),
	maCBCS VARCHAR(10),
	CONSTRAINT pk_CBCSNotMem_maCBCSNotMem PRIMARY KEY (maCBCS_Not_Mem),
	CONSTRAINT fk_CBCSNotMem_maCBCS FOREIGN KEY (maCBCS)
	REFERENCES dbo.CBCS(maCBCS)
);


CREATE TABLE QuanLy(
	maQuanLy VARCHAR(10),
	soHieuCAND VARCHAR(10),
	tenTK VARCHAR(20),
	matKhau VARCHAR(20),
	soDienThoai VARCHAR(10),
	CONSTRAINT pk_QuanLy_maQuanLy PRIMARY KEY (maQuanLy)
);
GO
DROP TABLE QuanLy
CREATE TABLE Admin (
	maAdmin VARCHAR(10),
	maQuanLy VARCHAR(10),
	CONSTRAINT pk_Admin_maAdmin PRIMARY KEY (maAdmin),
	CONSTRAINT fk_Admin_maQuanLy FOREIGN KEY (maQuanLy)
	REFERENCES dbo.QuanLy(maQuanLy)
);
GO

CREATE TABLE CBQL(
	maCBQL VARCHAR(10),
	maQuanLy VARCHAR(10),
	CONSTRAINT pk_CBQL_maCBQL PRIMARY KEY (maCBQL),
	CONSTRAINT fk_CBQL_maCBQL FOREIGN KEY (maQuanLy)
	REFERENCES dbo.QuanLy(maQuanLy)
);
GO

CREATE TABLE LanhDao(
	maLanhDao VARCHAR(10),
	maQuanLy VARCHAR(10),
	CONSTRAINT pk_LanhDao_maLanhDao PRIMARY KEY (maLanhDao),
	CONSTRAINT fk_LanhDao_maLanhDao FOREIGN KEY (maQuanLy)
	REFERENCES dbo.QuanLy(maQuanLy)
);
GO

-- DROP TABLE LanhDao -> để xoá nếu cần

CREATE TABLE VK_VLN_CCHT (
	soHieuVK_VLN_CCHT VARCHAR(10),
	chungLoai NVARCHAR(20),
	nhanHieuVK_VLN_CCHT NVARCHAR(20),
	soLuong INT,
	donViTinh NVARCHAR(10),
	nuocSanXuat NVARCHAR(20),
	tinhTrang NVARCHAR(50),
 	CONSTRAINT pk_VKVLNCCHT_soHieuVK_VLN_CCHT PRIMARY KEY (soHieuVK_VLN_CCHT)
);



CREATE TABLE VK (
	maVK VARCHAR(10),
	soHieuVK_VLN_CCHT VARCHAR(10),
	CONSTRAINT pk_VK_maVK PRIMARY KEY (maVK),
	CONSTRAINT fk_VK_soHieuVKVLNCCHT FOREIGN KEY (soHieuVK_VLN_CCHT)
	REFERENCES dbo.VK_VLN_CCHT(soHieuVK_VLN_CCHT)
);
GO


CREATE TABLE VLN (
	maVLN VARCHAR(10),
	soHieuVK_VLN_CCHT VARCHAR(10),
	CONSTRAINT pk_VLN_maVLN PRIMARY KEY (maVLN),
	CONSTRAINT fk_VLN_soHieuVKVLNCCHT FOREIGN KEY (soHieuVK_VLN_CCHT)
	REFERENCES dbo.VK_VLN_CCHT(soHieuVK_VLN_CCHT)
);
GO

CREATE TABLE CCHT (
	maCCHT VARCHAR(10),
	soHieuVK_VLN_CCHT VARCHAR(10),
	CONSTRAINT pk_CCHT_maCCHT PRIMARY KEY (maCCHT),
	CONSTRAINT fk_CCHT_soHieuVKVLNCCHT FOREIGN KEY (soHieuVK_VLN_CCHT)
	REFERENCES dbo.VK_VLN_CCHT(soHieuVK_VLN_CCHT)
);
GO


CREATE TABLE GPSD (
	soGPSD VARCHAR(10),
	soHieuVK_VLN_CCHT VARCHAR(10),
	chungLoaiGPSD NVARCHAR(20),
	ngayCap DATE,
	ngayHetHan DATE,
	nguoiKy NVARCHAR(50),
 	CONSTRAINT pk_GPSD_soGPSD PRIMARY KEY (soGPSD),
	CONSTRAINT fk_GPSD_soHieuVKVLNCCHT FOREIGN KEY (soHieuVK_VLN_CCHT)
	REFERENCES dbo.VK_VLN_CCHT(soHieuVK_VLN_CCHT)
);



CREATE TABLE DanhSachMuon (
	maMuon VARCHAR(10),
	soHieuVK_VLN_CCHT VARCHAR(10),
	maCBCS VARCHAR(10),
 	CONSTRAINT pk_DanhSachMuon_maMuon PRIMARY KEY (maMuon),
	CONSTRAINT fk_DanhSachMuon_soHieuVKVLNCCHT FOREIGN KEY (soHieuVK_VLN_CCHT)
	REFERENCES dbo.VK_VLN_CCHT(soHieuVK_VLN_CCHT),
	CONSTRAINT fk_DanhSachMuon_maCBCS FOREIGN KEY (maCBCS)
	REFERENCES dbo.CBCS(maCBCS)
);

-- drop table DanhSachMuon

CREATE TABLE DuyetMuon (
	maDuyet VARCHAR(10),
	maLanhDao VARCHAR(10),
	maCBQL VARCHAR(10),
	maMuon VARCHAR(10),
 	CONSTRAINT pk_DuyetMuon_maDuyet PRIMARY KEY (maDuyet),
	CONSTRAINT fk_DuyetMuon_maLanhDao FOREIGN KEY (maLanhDao)
	REFERENCES dbo.QuanLy(maQuanLy),
	CONSTRAINT fk_BienBan_maCBQL FOREIGN KEY (maCBQL)
	REFERENCES dbo.QuanLy(maQuanLy),
	CONSTRAINT fk_DuyetMuon_maMuon FOREIGN KEY (maMuon)
	REFERENCES dbo.DanhSachMuon(maMuon)
);



CREATE TABLE BienBan (
	soBienBan VARCHAR(10),
 	maDuyet VARCHAR(10),
	ngayMuon DATE,
	CONSTRAINT pk_BienBan_soBienBan PRIMARY KEY (soBienBan),
	CONSTRAINT fk_BienBan_maDuyet FOREIGN KEY (maDuyet)
	REFERENCES dbo.DuyetMuon(maDuyet),
);


CREATE TABLE PhieuTra (
	maTra VARCHAR(10),
	soBienBan VARCHAR(10),
	ngayTra DATE,
	CONSTRAINT pk_PhieuTra_maTra  PRIMARY KEY (maTra),
	CONSTRAINT fk_PhieuTra_soBienBan FOREIGN KEY (soBienBan)
	REFERENCES dbo.BienBan(soBienBan)
);

